apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: activemqtest
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - activemqtest.dev.insee.io
  rules:
    - host: activemqtest.dev.insee.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: activemqtest
                port:
                  number: 8080
